basePath: /api/v1/team/{team_id}/player
host: localhost:8080
info:
  contact: {}
  description: Para obtener los jugadores de los equipos desde Hattick y la base de
    datos.
  title: Players BACK API
  version: "1.0"
paths: {}
swagger: "2.0"
