name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2    

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Extract repository name
      id: extract_repo     
      run: echo "repo_name=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV

    - name: Remove existing directory if it exists
      run: |
        set -x
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          rm -rf ~/workspace/new-hattrick/${{ env.repo_name  }}
        "

    - name: Create directory
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          mkdir -p ~/workspace/new-hattrick/${{ env.repo_name }}
        "   

    - name: Copy files to remote server
      run: |
        set -e
        pwd
        ls -l
        scp -r -o StrictHostKeyChecking=no "$(pwd)"/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/workspace/new-hattrick/${{ env.repo_name }}

    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd ~/workspace/new-hattrick/${{ env.repo_name }} &&
          export ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} &&
          export CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }} &&
          export CONSUMER_KEY=${{ secrets.CONSUMER_KEY }} &&
          export OAUTH1_TOKEN=${{ secrets.OAUTH1_TOKEN }} &&
          export OAUTH1_TOKEN_SECRET=${{ secrets.OAUTH1_TOKEN_SECRET }} &&          
          export DB_POSTGRES_HOST=${{ secrets.DB_POSTGRES_HOST }} &&
          export DB_POSTGRES_PASS=${{ secrets.DB_POSTGRES_PASS }} &&
          export DB_POSTGRES_USER=${{ secrets.DB_POSTGRES_USER }} &&
          docker-compose up --build -d --force-recreate
        "
